{
  pkgs,
  inputs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    fd
    tldr
    tuba
    gimp
    heroic
    aspell
    killall
    ripgrep
    inkscape
    r2modman
    pciutils
    monophony
    alejandra
    grapejuice
    impression
    libreoffice
    virt-manager
    wl-clipboard
    protontricks
    prismlauncher
    android-studio
    mission-center
    nodePackages_latest.pnpm
    hunspellDicts.en_CA-large
    inputs.nix-gaming.packages.${system}.wine-ge
  ];
}
